### ISSUE TITLE
能否增加同一个分支不通版本的差异报告呢

### ISSUE THREAD

**Issue by shidilii** [512433465/JacocoPlus#1]

**Comment by 512433465** [comment]
> _No description provided._

同一个分支不通版本的差异报告，生成方法一样啊，你看我下面的示例代码有的。支持的。

目前我这边也在调试。

**Comment by shidilii** [comment]
好的 正在看，你这份代码解决了我很多问题，很棒

**Comment by 512433465** [comment]
我也是刚研究，欢迎一起共同开发研究




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shidilii"<notifications@github.com&gt;; 
发送时间: 2019年10月22日(星期二) 下午2:23
收件人: "512433465/JacocoPlus"<JacocoPlus@noreply.github.com&gt;; 
抄送: "吟啸徐行"<512433465@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [512433465/JacocoPlus] 能否增加同一个分支不通版本的差异报告呢 (#1)




好的 正在看，你这份代码解决了我很多问题，很棒

**Comment by loserwyx** [comment]
> 好的 正在看，你这份代码解决了我很多问题，很棒

您好，我目前在研究基于jacoco增量覆盖率的实现方法，我借用了作者的一些代码，但是在本地运行的时候出现了以下的情况，能帮忙看一下么 ，感谢，感谢！
![image](https://user-images.githubusercontent.com/20351432/83048612-6fc82d00-a07c-11ea-8d07-a4d91f7d6104.png)
