### ISSUE TITLE
jacococli打出的包main方法的类信息没有添加到manifest

### ISSUE THREAD

**Issue by wlxzd** [512433465/JacocoPlus#10]
jacococli打出的包main方法的类信息没有添加到manifest，pom文件已经做main-class配置了，请教下

**Comment by 512433465** [comment]
使用方法：

一，Jacoco包的配置(具体配置百度Jacoco的Tomcat配置)
1，懒伸手党模式：使用我二次开发后上传的Release包代替自己下载的Jacoco包。
2，自己动手模式：下载我的代码，执行mvn clean package -Dmaven.javadoc.test=true -Dmaven.test.skip=true自行打包。注意事项IDE下载后，在IDE中执行maven打包命令可能不成功。 建议在命令行中执行maven打包命令。打包成功后，用官网包lib/jacocoagent.jar 替换自己新打包生成的jacocoagent.jar文件，否则可能引起Tomcat无法启动。
