### ISSUE TITLE
本地执行readme示例代码报错

### ISSUE THREAD

**Issue by loserwyx** [512433465/JacocoPlus#12]
您好，我目前在研究基于jacoco增量覆盖率的实现方法，我借用了您的一些代码，但是在本地运行的时候出现了以下的情况，能帮忙看一下么 ，感谢，感谢！
![image](https://user-images.githubusercontent.com/20351432/83048612-6fc82d00-a07c-11ea-8d07-a4d91f7d6104.png)

**Comment by 512433465** [comment]
完全按照代码的说明做的么？
