### ISSUE TITLE
为什么要替换jacocoanent.jar

### ISSUE THREAD

**Issue by furionwu** [512433465/JacocoPlus#14]
2，自己动手模式：下载我的代码，执行mvn clean package -Dmaven.javadoc.test=true -Dmaven.test.skip=true自行打包。注意事项IDE下载后，在IDE中执行maven打包命令可能不成功。 建议在命令行中执行maven打包命令。打包成功后，用官网包lib/jacocoagent.jar 替换自己新打包生成的jacocoagent.jar文件，否则可能引起Tomcat无法启动。-----z这是为什么嘛，我就是要用生成的jacocoanent.jar呢

**Comment by 512433465** [comment]
不是必须的，看启动是否报错。
