### ISSUE TITLE
目前支持多模块的项目么

### ISSUE THREAD

**Issue by 15301117679** [512433465/JacocoPlus#2]
代码部署后收集覆盖率， 新分支可能还在一直的提交代码，这样收集覆盖率阶段， 新分支 和 master 代码 diff 可能 与 之前的代码不一致，会出问题。

建议，用 提交的 版本号 做diff 这样可以保证代码准确性。

297766856 加 qq 一起 讨论下

**Comment by 512433465** [comment]
版本号可以用Tag控制。这样不知道能不能满足你的需求。

**Comment by 512433465** [comment]
后期追加一个基于版本号差分的对比吧

**Comment by 15301117679** [comment]
实践发现，新增的代码可以识别，即没被标记，不会显示颜色，可以区分，不影响使用。
