### ISSUE TITLE
JGit代码检出不能自动合并，命令git pull 可以自动Merge.

### ISSUE THREAD

**Issue by 15301117679** [512433465/JacocoPlus#3]
报错：Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files:

报错代码： 
        //  拉取最新代码
        git.pull().setCredentialsProvider(usernamePasswordCredentialsProvider).call();
报错原因：
        JGit 对于代码检出自动合并Merge支持不好，看看有解决方案么
下下策解决方案：
       脚本+命令 远程执行

**Comment by 512433465** [comment]
脚本+命令 远程执行
是个很好的解决方案吧

**Comment by shidilii** [comment]
> 报错：Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files:
> 
> 报错代码：
> // 拉取最新代码
> git.pull().setCredentialsProvider(usernamePasswordCredentialsProvider).call();
> 报错原因：
> JGit 对于代码检出自动合并Merge支持不好，看看有解决方案么
> 下下策解决方案：
> 脚本+命令 远程执行

你的脚本+命令远程执行是怎么做的呢？我现在是先删除再整个项目在checkout整个项目

**Comment by 15301117679** [comment]
第一步： linux 服务器上写 shell 脚本 pull 代码，整一个 .sh 文件；


第二步：开发环境执行 远程调用 shell 脚本；

完成以上2步，就实现 pull 拉取 最新代码了。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shidilii"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 下午3:15
收件人:&nbsp;"512433465/JacocoPlus"<JacocoPlus@noreply.github.com&gt;;
抄送:&nbsp;"╭惜一丝冷清"<297766856@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [512433465/JacocoPlus] JGit代码检出不能自动合并，命令git pull 可以自动Merge. (#3)



 
报错：Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files:
 
报错代码：
 // 拉取最新代码
 git.pull().setCredentialsProvider(usernamePasswordCredentialsProvider).call();
 报错原因：
 JGit 对于代码检出自动合并Merge支持不好，看看有解决方案么
 下下策解决方案：
 脚本+命令 远程执行
  
你的脚本+命令远程执行是怎么做的呢？我现在是先删除再整个项目在checkout整个项目

**Comment by 512433465** [comment]
> 第一步： linux 服务器上写 shell 脚本 pull 代码，整一个 .sh 文件； 第二步：开发环境执行 远程调用 shell 脚本； 完成以上2步，就实现 pull 拉取 最新代码了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"shidilii"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月25日(星期一) 下午3:15 收件人:&nbsp;"512433465/JacocoPlus"<JacocoPlus@noreply.github.com&gt;; 抄送:&nbsp;"╭惜一丝冷清"<297766856@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [512433465/JacocoPlus] JGit代码检出不能自动合并，命令git pull 可以自动Merge. (#3) 报错：Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 报错代码： // 拉取最新代码 git.pull().setCredentialsProvider(usernamePasswordCredentialsProvider).call(); 报错原因： JGit 对于代码检出自动合并Merge支持不好，看看有解决方案么 下下策解决方案： 脚本+命令 远程执行 你的脚本+命令远程执行是怎么做的呢？我现在是先删除再整个项目在checkout整个项目 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不错的主意
