### ISSUE TITLE
是否支持两个commit的diff呢？

### ISSUE THREAD

**Issue by sxyy** [512433465/JacocoPlus#6]
看了下对比的方式，一个是分支跟分支，还有tag跟tag的比较，怎么使用才能够支持两个commit的diff呢？

**Comment by RayPengzhihui** [comment]
tag跟tag之间的对比与commit的对比方式是一样的。按照道理来说你传两个commit运行是一样可以成功的

**Comment by 512433465** [comment]
也是可以的。上次有朋友也问这问题了，他已经实现了，你试试，我最近忙代码没有搞




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sxyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午4:32
收件人:&nbsp;"512433465/JacocoPlus"<JacocoPlus@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[512433465/JacocoPlus] 是否支持两个commit的diff呢？ (#6)




看了下对比的方式，一个是分支跟分支，还有tag跟tag的比较，怎么使用才能够支持两个commit的diff呢？

**Comment by sxyy** [comment]
@RayPengzhihui  @512433465  我试了下 确实 tag跟tag的对比 确实就可以搞定
另外想再问一个问题:
我们这边可能需要比较test分支的某一个commit跟 release分支某个commit的比较，这种是否也同样可以使用tag tag之间的比较呢？ 因为我尝试了，确实也能出结果。感觉这块其实跟分支关系不是很大。

**Comment by 512433465** [comment]
这个我没有试过。
另外有好想法，可以提交一下，共同开发维护一下，这个开源项目

**Comment by loserwyx** [comment]
> @RayPengzhihui @512433465 我试了下 确实 tag跟tag的对比 确实就可以搞定
> 另外想再问一个问题:
> 我们这边可能需要比较test分支的某一个commit跟 release分支某个commit的比较，这种是否也同样可以使用tag tag之间的比较呢？ 因为我尝试了，确实也能出结果。感觉这块其实跟分支关系不是很大。

您好，我目前在研究基于jacoco增量覆盖率的实现方法，我借用了作者的一些代码，但是在本地运行的时候出现了以下的情况，能帮忙看一下么 ，感谢，感谢！
![image](https://user-images.githubusercontent.com/20351432/83048612-6fc82d00-a07c-11ea-8d07-a4d91f7d6104.png)
