### ISSUE TITLE
在哪里传递新旧tag参数给jacoco?

### ISSUE THREAD

**Issue by ZhangKe4042602** [512433465/JacocoPlus#7]
jacoco 新手一枚。十分感谢您二次开发的jacoco增量覆盖率的统计功能，但是太清楚怎么使用,在哪里接受传递的newTag和oldTag，请教你是怎么使用的，是用maven，Jenkins还是怎么整合，然后接受传递的参数的，我看网上maven的都是单元测试的，直接mvn install 执行测试生成报告了。但是我想做的是手动测试的增量代码覆盖率，应该怎么做呢？十分感激

**Comment by ZhangKe4042602** [comment]
> jacoco 新手一枚。十分感谢您二次开发的jacoco增量覆盖率的统计功能，但是太清楚怎么使用,在哪里接受传递的newTag和oldTag，请教你是怎么使用的，是用maven，Jenkins还是怎么整合，然后接受传递的参数的，我看网上maven的都是单元测试的，直接mvn install 执行测试生成报告了。但是我想做的是手动测试的增量代码覆盖率，应该怎么做呢？十分感激

我又看了一下readme中的例子，说一下自己的理解。首先在运行服务的Tomcat上配置Tomcat，以便程序运行时获取执行信息，便于后面的覆盖率的计算。第二部是从远端获取jacoco的exec文件到本地(或者另一个服务器上)，使用newTag和oldTag方法生成报表中的。

**Comment by 512433465** [comment]
你理解的很对，就是这么干的，这样既能满足你手动生成，又可以灵活的集成进平台。

**Comment by ListeningL** [comment]
> > jacoco 新手一枚。十分感谢您二次开发的jacoco增量覆盖率的统计功能，但是太清楚怎么使用,在哪里接受传递的newTag和oldTag，请教你是怎么使用的，是用maven，Jenkins还是怎么整合，然后接受传递的参数的，我看网上maven的都是单元测试的，直接mvn install 执行测试生成报告了。但是我想做的是手动测试的增量代码覆盖率，应该怎么做呢？十分感激
> 
> 我又看了一下readme中的例子，说一下自己的理解。首先在运行服务的Tomcat上配置Tomcat，以便程序运行时获取执行信息，便于后面的覆盖率的计算。第二部是从远端获取jacoco的exec文件到本地(或者另一个服务器上)，使用newTag和oldTag方法生成报表中的。

请问下，坐着的代码中并没有指定需要对比的两个分支，执行时是怎么判断的呢，我其实只想去解析exec文件生成报告，不需要指定remote以及数据库信息，如果要实现这个需求呢
