### ISSUE TITLE
使用tcpserver方式如何追加覆盖率文件

### ISSUE THREAD

**Issue by zengxiaoliang** [512433465/JacocoPlus#9]
使用 ExecutionDataClient 生成的结果文件默认为 项目启动到当前这段时间的覆盖率数据；
项目重启后如何在之前的覆盖率文件上追加？

我个人尝试了如下方式：

final FileOutputStream localFile = new FileOutputStream(DESTFILE,true);

结果：
新导出文件追加写到上次的覆盖率文件中，但生成报告并不包含最新测试的覆盖率数据

**Comment by sxyy** [comment]
你应该是自己的服务保留一份jacoco.exec的文件，项目重启以后，你应该是重新拉去一份新的exec,然后将旧的跟新的做一个merge就好

**Comment by sxyy** [comment]
你应该是自己的服务保留一份jacoco.exec的文件，项目重启以后，你应该是重新拉去一份新的exec,然后将旧的跟新的做一个merge就好

**Comment by zengxiaoliang** [comment]
> 你应该是自己的服务保留一份jacoco.exec的文件，项目重启以后，你应该是重新拉去一份新的exec,然后将旧的跟新的做一个merge就好

旧的我保留了，新的也能拿到；
请问如何进行merge呢？

**Comment by zengxiaoliang** [comment]
> > 你应该是自己的服务保留一份jacoco.exec的文件，项目重启以后，你应该是重新拉去一份新的exec,然后将旧的跟新的做一个merge就好
> 
> 旧的我保留了，新的也能拿到；
> 请问如何进行merge呢？

看到了，jacoco 里面支持merge 操作
